export const breednames=[
"Affenpinscher",
"African",
"Airedale",
"Akita",
"Appenzeller",
"Kelpie Australian",
"Shepherd Australian",
"Indian Bakharwal",
"Basenji",
"Beagle",
"Bluetick",
"Borzoi",
"Bouvier",
"Boxer",
"Brabancon",
"Briard",
"Norwegian Buhund",
"Boston Bulldog",
"English Bulldog",
"French Bulldog",
"Staffordshire Bullterrier",
"Australian Cattledog",
"Cavapoo",
"Chihuahua",
"Indian Chippiparai",
"Chow",
"Clumber",
"Cockapoo",
"Border Collie",
"Coonhound",
"Cardigan Corgi",
"Cotondetulear",
"Dachshund",
"Dalmatian",
"Great Dane",
"Swedish Danish",
"Scottish Deerhound",
"Dhole",
"Dingo",
"Doberman",
"Norwegian Elkhound",
"Entlebucher",
"Eskimo",
"Lapphund Finnish",
"Bichon Frise",
"Indian Gaddi",
"Germanshepherd",
"Indian Greyhound",
"Italian Greyhound",
"Groenendael",
"Havanese",
"Afghan Hound",
"Basset Hound",
"Blood Hound",
"English Hound",
"Ibizan Hound",
"Plott Hound",
"Walker Hound",
"Husky",
"Keeshond",
"Kelpie",
"Kombai",
"Komondor",
"Kuvasz",
"Labradoodle",
"Labrador",
"Leonberg",
"Lhasa",
"Malamute",
"Malinois",
"Maltese",
"Bull Mastiff",
"English Mastiff",
"Indian Mastiff",
"Tibetan Mastiff",
"Mexicanhairless",
"Mix",
"Bernese Mountain",
"Swiss Mountain",
"Indian Mudhol",
"Newfoundland",
"Otterhound",
"Caucasian Ovcharka",
"Papillon",
"Indian Pariah",
"Pekinese",
"Pembroke",
"Miniature Pinscher",
"Pitbull",
"German Pointer",
"Germanlonghair Pointer",
"Pomeranian",
"Medium Poodle",
"Miniature Poodle",
"Standard Poodle",
"Toy Poodle",
"Pug",
"Puggle",
"Pyrenees",
"Indian Rajapalayam",
"Redbone",
"Chesapeake Retriever",
"Curly Retriever",
"Flatcoated Retriever",
"Golden Retriever",
"Rhodesian Ridgeback",
"Rottweiler",
"Saluki",
"Samoyed",
"Schipperke",
"Giant Schnauzer",
"Miniature Schnauzer",
"Italian Segugio",
"English Setter",
"Gordon Setter",
"Irish Setter",
"Sharpei",
"English Sheepdog",
"Indian Sheepdog",
"Shetland Sheepdog",
"Shiba",
"Shihtzu",
"Blenheim Spaniel",
"Brittany Spaniel",
"Cocker Spaniel",
"Irish Snaniel",
"Japanese Spaniel",
"Sussex Spaniel",
"Welsh Spaniel",
"Indian Spitz",
"Japanese Spitz",
"English Springer",
"Stbernard",
"American Terrier",
"Australian Terrier",
"Bedlington Terrier",
"Border Terrier",
"Cairn Terrier",
"Dandie Terrier",
"Fox Terrier",
"Irish Terrier",
"Kerryblue Terrier",
"Lakeland Terrier",
"Norfolk Terrier",
"Norwich Terrier",
"Patterdale Terrier",
"Russell Terrier",
"Scottish Terrier",
"Sealyham Terrier",
"Silky Terrier",
"Tibetan Terrier",
"Toy Terrier",
"Welsh Terrier",
"Westhighland Terrier",
"Wheaten Terrier",
"Yorkshire Terrier",
"Tervuren",
"Vizsla",
"Spanish Waterdog",
"Weimaraner",
"Whippet",
"Irish Wolfhound"
]